### ISSUE TITLE
Mechanism to load problem pddl files

### ISSUE THREAD

**Issue by paucarre** [IntelligentRoboticsLabs/plansys2_cooking_experiment#1]
Thanks for the example and all the work in PlanSys2 !

I'd like to know if there is a way to load directly upon launch the **problem pddl** to the **problem expert** node. Namely, load to the problem expert node one of the files: **cooking_problem_0.pddl**, .., **cooking_problem_3.pddl**

As far as I see, the **problem expert** node launch requires the **domain pddl**, which seems to configure the **domain expert**. 
Is there any way the **problem expert** node can directly load the **problem pddl** directly using a configuration parameter upon launch?

Side question: as the **domain expert** gets **domain pddl**  in its launch configuration, shouldn't the **problem expert node** just get the **problem pddl** as configuration and rely on the **domain** **expert** configured **domain** **pddl?**

**Comment by fmrico** [comment]
Hi @paucarre 

Your question is really interesting. It would be very useful to init the knowledge from a problem pddl, or even from a YAML file. In my examples, I use the controllers (executables that use the problem_expert client to insert knowledge).

If you want to work on that and prepare a PR, I can guide and help you.

Thanks for using PlanSys2 :)
